version: '3'
services:
  mongo:
    build:
    restart:
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
      MONGO_REPLICA_HOST:
      MONGO_REPLICA_PORT:
    ports:
      - 
